### ISSUE TITLE
Create app.put(api/apps/appName/canary) route

### ISSUE THREAD

**Issue by samlipari** [Sentinel-PaaS/sentinel-api#17]

**Comment by MFatigati** [comment]
Well, good news! Sam and I were able to get the database with canary working on my computer, with a fresh initialization. We did start getting funny results from the weighted load balancer with higher numbers. It seems like having the canary at 1, and the production service at, e.g., 3, was much less buggy for some reason. Perhaps we can still accept a percentage for the canary, but then convert that to a smaller fraction. So if they say they was 30% of traffic routed to the canary, we say 30/100 = 1/x, where x represents the production weight.

**Comment by dsessler7** [comment]
As I understand it, Sam adjusted the traffic weight stuff so that it uses the lowest common denominator, so I'm closing this.
