### ISSUE TITLE
Update ansible config

### ISSUE THREAD

**Issue by Brendan-Leal** [Sentinel-PaaS/sentinel-api#34]
When a request is issued to `/api/cluster/initialize` this kicks off the creation of the docker swarm. Starting first with creating the EC2 instances with terraform followed by provisioning the rest of the infrastructure with ansible. The ansible plays happen immediately after terraform _**too**_ quickly and there isn't enough time between the the EC2 instance coming up and executing ansible plays. As a consequence ansible makes a single attempt to connect to the manager node, via ssh, and **fails** because the instance isn't available immediately. I ran into this same issue on the CLI side of things and the solution was to add this to the anisble config:
```
[ssh_connection]
retries=3
```
This tells ansible, "try and connect to the node and if you fail try again up to 3 times."

**Comment by dsessler7** [comment]
I also added a "sleep" function (setTimeout inside an awaited promise) and set it to 10 seconds. Even with the retries at 3 it would eventually get enough failed connection attempts that AWS would lock me out.
