### ISSUE TITLE
open up port 9090 to api server

### ISSUE THREAD

**Issue by MFatigati** [Sentinel-PaaS/sentinel-api#55]
We need to change the `tf_docker_api` security group to `tf_docker_prometheus_api`, and add port 9090 to be open to the API server, in the same way as with docker. Now that the prometheus domain is behind a password, we need to access the port directly, e.g.:

```
let data = await AXIOS.get(`http://${managerIP}:9090/api/v1/query`, {
  params: {
    query: "node_filesystem_avail_bytes"
  },
  httpsAgent: agent
});
```

I changed this manually in my AWS account, and it works, so I hope its not too much to modify the security group in this way?

**Comment by dsessler7** [comment]
I presume this only needs to happen on the Manager? Should it also be set to only accept connections from the API server or should the port be open to everyone?

**Comment by MFatigati** [comment]
Yes, only on the manager, and only open to the API server. So, the same as as with the Docker API.
