### ISSUE TITLE
Implement app.get(api/apps/appName)

### ISSUE THREAD

**Issue by samlipari** [Sentinel-PaaS/sentinel-api#8]
For the requested application, response includes
Current scale
app name
health status (whether its up and link to prometheus/grafana)
whether there is a canary version

**Comment by MFatigati** [comment]
Currently, by combining/filtering data from `listServices` and `listContainers`, we're able to get a "service status" result that looks like this:

![Screen Shot 2022-03-25 at 7 59 03 PM](https://user-images.githubusercontent.com/28897430/160215936-243a5b79-ab5e-41ec-bdb0-e2806782cb08.png)

Still need to integrate prometheus and grafana routes.

**Comment by MFatigati** [comment]
You can get that result just by typing in the name "catnip_production". So for any services with a canary, you get both, but otherwise you just get the one.
